yaname: Compilar GestorMasterS APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17 (Obligatorio para API 33)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar paquetes base del sistema
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libffi-dev libssl-dev cmake ncurses-dev libncurses5-dev libncursesw5-dev

      - name: Usar Python 3.10 Exacto
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.14'

      - name: Instalar dependencias de Python modernas
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install cython==0.29.37 buildozer==1.5.0 sh

      - name: Crear buildozer.spec CORREGIDO
        run: |
          cat << 'EOF' > buildozer.spec
          [app]
          title = GestorMasterS
          package.name = gestormasters
          packa
